# -*- coding: utf-8 -*-
"""Day_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W2-SyYIfca9upzfZ76zuz3VaaQEsw0ye
"""

x = [int(i) for i in input('persons given gifts to: ').split()]
for j in range(len(x)):
  for k in range(len(x)):
    if (j+1) == x[k]:
      print(f"{k+1} ", end="")